In [157]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os,json
from sklearn.preprocessing import OneHotEncoder

In [158]:
sh_info = pd.read_csv('Data/superhero_info.csv')
sh_powers = pd.read_csv('Data/superhero_powers.csv')

# SuperHero info

In [159]:
sh_info

,Hero|Publisher,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements
0,A-Bomb|Marvel Comics,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"
1,Abe Sapien|Dark Horse Comics,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}"
2,Abin Sur|DC Comics,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}"
3,Abomination|Marvel Comics,Male,Human / Radiation,bad,No Hair,green,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"
4,Absorbing Man|Marvel Comics,Male,Human,bad,No Hair,blue,Unknown,"{'Height': '193.0 cm', 'Weight': '122.0 kg'}"
...,...,...,...,...,...,...,...,...
458,Yellowjacket|Marvel Comics,Male,Human,good,Blond,blue,Unknown,"{'Height': '183.0 cm', 'Weight': '83.0 kg'}"
459,Yellowjacket II|Marvel Comics,Female,Human,good,Strawberry Blond,blue,Unknown,"{'Height': '165.0 cm', 'Weight': '52.0 kg'}"
460,Yoda|George Lucas,Male,Yoda's species,good,White,brown,green,"{'Height': '66.0 cm', 'Weight': '17.0 kg'}"
461,Zatanna|DC Comics,Female,Human,good,Black,blue,Unknown,"{'Height': '170.0 cm', 'Weight': '57.0 kg'}"
462,Zoom|DC Comics,Male,Unknown,bad,Brown,red,Unknown,"{'Height': '185.0 cm', 'Weight': '81.0 kg'}"

In [160]:
sh_powers

          hero_names                                             Powers
0            3-D Man         Agility,Super Strength,Stamina,Super Speed
1             A-Bomb  Accelerated Healing,Durability,Longevity,Super...
2         Abe Sapien  Agility,Accelerated Healing,Cold Resistance,Du...
3           Abin Sur                                 Lantern Power Ring
4        Abomination  Accelerated Healing,Intelligence,Super Strengt...
..               ...                                                ...
662  Yellowjacket II                 Flight,Energy Blasts,Size Changing
663             Ymir  Cold Resistance,Durability,Longevity,Super Str...
664             Yoda  Agility,Stealth,Danger Sense,Marksmanship,Weap...
665          Zatanna  Cryokinesis,Telepathy,Magic,Fire Control,Proba...
666             Zoom  Super Speed,Intangibility,Time Travel,Time Man...

[667 rows x 2 columns]

In [161]:
sh_info[['Hero', 'Publisher']] = sh_info['Hero|Publisher'].str.split('|', expand=True)
sh_info.drop(columns='Hero|Publisher',inplace=True)
sh_info[['Hero', 'Publisher']]

                Hero          Publisher
0             A-Bomb      Marvel Comics
1         Abe Sapien  Dark Horse Comics
2           Abin Sur          DC Comics
3        Abomination      Marvel Comics
4      Absorbing Man      Marvel Comics
..               ...                ...
458     Yellowjacket      Marvel Comics
459  Yellowjacket II      Marvel Comics
460             Yoda       George Lucas
461          Zatanna          DC Comics
462             Zoom          DC Comics

[463 rows x 2 columns]

In [162]:
shee = pd.DataFrame()
shee['Mes'] = sh_info['Measurements'].apply(pd.Series)
shee

                                              Mes
0    {'Height': '203.0 cm', 'Weight': '441.0 kg'}
1     {'Height': '191.0 cm', 'Weight': '65.0 kg'}
2     {'Height': '185.0 cm', 'Weight': '90.0 kg'}
3    {'Height': '203.0 cm', 'Weight': '441.0 kg'}
4    {'Height': '193.0 cm', 'Weight': '122.0 kg'}
..                                            ...
458   {'Height': '183.0 cm', 'Weight': '83.0 kg'}
459   {'Height': '165.0 cm', 'Weight': '52.0 kg'}
460    {'Height': '66.0 cm', 'Weight': '17.0 kg'}
461   {'Height': '170.0 cm', 'Weight': '57.0 kg'}
462   {'Height': '185.0 cm', 'Weight': '81.0 kg'}

[463 rows x 1 columns]

In [163]:
shee[['H','W']] = shee['Mes'].str.split(', ', expand=True)
shee = shee.drop(columns='Mes')
shee

                         H                      W
0    {'Height': '203.0 cm'  'Weight': '441.0 kg'}
1    {'Height': '191.0 cm'   'Weight': '65.0 kg'}
2    {'Height': '185.0 cm'   'Weight': '90.0 kg'}
3    {'Height': '203.0 cm'  'Weight': '441.0 kg'}
4    {'Height': '193.0 cm'  'Weight': '122.0 kg'}
..                     ...                    ...
458  {'Height': '183.0 cm'   'Weight': '83.0 kg'}
459  {'Height': '165.0 cm'   'Weight': '52.0 kg'}
460   {'Height': '66.0 cm'   'Weight': '17.0 kg'}
461  {'Height': '170.0 cm'   'Weight': '57.0 kg'}
462  {'Height': '185.0 cm'   'Weight': '81.0 kg'}

[463 rows x 2 columns]

# SuperHero Powers

In [164]:
sh_powers

          hero_names                                             Powers
0            3-D Man         Agility,Super Strength,Stamina,Super Speed
1             A-Bomb  Accelerated Healing,Durability,Longevity,Super...
2         Abe Sapien  Agility,Accelerated Healing,Cold Resistance,Du...
3           Abin Sur                                 Lantern Power Ring
4        Abomination  Accelerated Healing,Intelligence,Super Strengt...
..               ...                                                ...
662  Yellowjacket II                 Flight,Energy Blasts,Size Changing
663             Ymir  Cold Resistance,Durability,Longevity,Super Str...
664             Yoda  Agility,Stealth,Danger Sense,Marksmanship,Weap...
665          Zatanna  Cryokinesis,Telepathy,Magic,Fire Control,Proba...
666             Zoom  Super Speed,Intangibility,Time Travel,Time Man...

[667 rows x 2 columns]

In [165]:
sh_powers.rename(columns={'hero_names':'Hero'},  inplace=True)
sh_powers

                Hero                                             Powers
0            3-D Man         Agility,Super Strength,Stamina,Super Speed
1             A-Bomb  Accelerated Healing,Durability,Longevity,Super...
2         Abe Sapien  Agility,Accelerated Healing,Cold Resistance,Du...
3           Abin Sur                                 Lantern Power Ring
4        Abomination  Accelerated Healing,Intelligence,Super Strengt...
..               ...                                                ...
662  Yellowjacket II                 Flight,Energy Blasts,Size Changing
663             Ymir  Cold Resistance,Durability,Longevity,Super Str...
664             Yoda  Agility,Stealth,Danger Sense,Marksmanship,Weap...
665          Zatanna  Cryokinesis,Telepathy,Magic,Fire Control,Proba...
666             Zoom  Super Speed,Intangibility,Time Travel,Time Man...

[667 rows x 2 columns]

In [166]:
sh_powers['Powers'] = sh_powers['Powers'].str.replace(" ",'_')

sh_powers['Powers'] = sh_powers['Powers'].str.replace(",",' ')

sh_powers

                Hero                                             Powers
0            3-D Man         Agility Super_Strength Stamina Super_Speed
1             A-Bomb  Accelerated_Healing Durability Longevity Super...
2         Abe Sapien  Agility Accelerated_Healing Cold_Resistance Du...
3           Abin Sur                                 Lantern_Power_Ring
4        Abomination  Accelerated_Healing Intelligence Super_Strengt...
..               ...                                                ...
662  Yellowjacket II                 Flight Energy_Blasts Size_Changing
663             Ymir  Cold_Resistance Durability Longevity Super_Str...
664             Yoda  Agility Stealth Danger_Sense Marksmanship Weap...
665          Zatanna  Cryokinesis Telepathy Magic Fire_Control Proba...
666             Zoom  Super_Speed Intangibility Time_Travel Time_Man...

[667 rows x 2 columns]

# SH_df

In [167]:
sh_df = pd.merge(sh_powers, sh_info, on='Hero')

In [168]:
sh_df

,Hero,Powers,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements,Publisher
0,A-Bomb,Accelerated_Healing Durability Longevity Super...,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",Marvel Comics
1,Abe Sapien,Agility Accelerated_Healing Cold_Resistance Du...,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}",Dark Horse Comics
2,Abin Sur,Lantern_Power_Ring,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}",DC Comics
3,Abomination,Accelerated_Healing Intelligence Super_Strengt...,Male,Human / Radiation,bad,No Hair,green,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",Marvel Comics
4,Absorbing Man,Cold_Resistance Durability Energy_Absorption S...,Male,Human,bad,No Hair,blue,Unknown,"{'Height': '193.0 cm', 'Weight': '122.0 kg'}",Marvel Comics
...,...,...,...,...,...,...,...,...,...,...
458,Yellowjacket,Size_Changing Animal_Oriented_Powers,Male,Human,good,Blond,blue,Unknown,"{'Height': '183.0 cm', 'Weight': '83.0 kg'}",Marvel Comics
459,Yellowjacket II,Flight Energy_Blasts Size_Changing,Female,Human,good,Strawberry Blond,blue,Unknown,"{'Height': '165.0 cm', 'Weight': '52.0 kg'}",Marvel Comics
460,Yoda,Agility Stealth Danger_Sense Marksmanship Weap...,Male,Yoda's species,good,White,brown,green,"{'Height': '66.0 cm', 'Weight': '17.0 kg'}",George Lucas
461,Zatanna,Cryokinesis Telepathy Magic Fire_Control Proba...,Female,Human,good,Black,blue,Unknown,"{'Height': '170.0 cm', 'Weight': '57.0 kg'}",DC Comics
462,Zoom,Super_Speed Intangibility Time_Travel Time_Man...,Male,Unknown,bad,Brown,red,Unknown,"{'Height': '185.0 cm', 'Weight': '81.0 kg'}",DC Comics

In [169]:
sh_df['Powers'].value_counts

<bound method IndexOpsMixin.value_counts of 0      Accelerated_Healing Durability Longevity Super...
1      Agility Accelerated_Healing Cold_Resistance Du...
2                                     Lantern_Power_Ring
3      Accelerated_Healing Intelligence Super_Strengt...
4      Cold_Resistance Durability Energy_Absorption S...
                             ...
458                 Size_Changing Animal_Oriented_Powers
459                   Flight Energy_Blasts Size_Changing
460    Agility Stealth Danger_Sense Marksmanship Weap...
461    Cryokinesis Telepathy Magic Fire_Control Proba...
462    Super_Speed Intangibility Time_Travel Time_Man...
Name: Powers, Length: 463, dtype: object>

In [170]:
sh_df['Measurements']

0      {'Height': '203.0 cm', 'Weight': '441.0 kg'}
1       {'Height': '191.0 cm', 'Weight': '65.0 kg'}
2       {'Height': '185.0 cm', 'Weight': '90.0 kg'}
3      {'Height': '203.0 cm', 'Weight': '441.0 kg'}
4      {'Height': '193.0 cm', 'Weight': '122.0 kg'}
                           ...
458     {'Height': '183.0 cm', 'Weight': '83.0 kg'}
459     {'Height': '165.0 cm', 'Weight': '52.0 kg'}
460      {'Height': '66.0 cm', 'Weight': '17.0 kg'}
461     {'Height': '170.0 cm', 'Weight': '57.0 kg'}
462     {'Height': '185.0 cm', 'Weight': '81.0 kg'}
Name: Measurements, Length: 463, dtype: object

In [171]:
Height = sh_df['Measurements'].str.extract(r'(\d+\.\d+)\s*(cm)')
Weight = sh_df['Measurements'].str.extract(r'(\d+\.\d+)\s*(kg)')

In [172]:
Weight[0] = Weight[0].astype(float)
Height[0] = Height[0].astype(float)

In [173]:
sh_df['Weight_kg'] = Weight[0]
sh_df['Height_cm'] = Height[0]

In [174]:
sh_df.drop(columns='Measurements', inplace=True)

In [175]:
sh_df[['Powers', 'Hero']]

                                                Powers             Hero
0    Accelerated_Healing Durability Longevity Super...           A-Bomb
1    Agility Accelerated_Healing Cold_Resistance Du...       Abe Sapien
2                                   Lantern_Power_Ring         Abin Sur
3    Accelerated_Healing Intelligence Super_Strengt...      Abomination
4    Cold_Resistance Durability Energy_Absorption S...    Absorbing Man
..                                                 ...              ...
458               Size_Changing Animal_Oriented_Powers     Yellowjacket
459                 Flight Energy_Blasts Size_Changing  Yellowjacket II
460  Agility Stealth Danger_Sense Marksmanship Weap...             Yoda
461  Cryokinesis Telepathy Magic Fire_Control Proba...          Zatanna
462  Super_Speed Intangibility Time_Travel Time_Man...             Zoom

[463 rows x 2 columns]

In [176]:
sh_df['Powers'].dtype

dtype('O')

# One Hot Encoder

In [177]:
df_out = pd.concat(
    [
        df["Hero"],
        df["Powers"].str.get_dummies(sep=" ")
    ],
    axis=1
)

sh_final = pd.merge(df_out, sh_df, on='Hero').drop(columns='Powers')

    1. Compare the average weight of super heros who have Super Speed to those who do not.

    2. What is the average height of heroes for each publisher?

In [178]:
sh_final

,Hero,Accelerated_Healing,Adaptation,Agility,Animal_Attributes,Animal_Control,Animal_Oriented_Powers,Animation,Anti-Gravity,Astral_Projection,...,Wind_Control,Gender,Race,Alignment,Hair color,Eye color,Skin color,Publisher,Weight_kg,Height_cm
0,A-Bomb,1,0,0,0,0,0,0,0,0,...,0,Male,Human,good,No Hair,yellow,Unknown,Marvel Comics,441.0,203.0
1,Abe Sapien,1,0,1,0,0,0,0,0,0,...,0,Male,Icthyo Sapien,good,No Hair,blue,blue,Dark Horse Comics,65.0,191.0
2,Abin Sur,0,0,0,0,0,0,0,0,0,...,0,Male,Ungaran,good,No Hair,blue,red,DC Comics,90.0,185.0
3,Abomination,1,0,0,0,0,0,1,0,0,...,0,Male,Human / Radiation,bad,No Hair,green,Unknown,Marvel Comics,441.0,203.0
4,Absorbing Man,0,0,0,0,0,0,0,0,0,...,0,Male,Human,bad,No Hair,blue,Unknown,Marvel Comics,122.0,193.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,Yellowjacket,0,0,0,0,0,1,0,0,0,...,0,Male,Human,good,Blond,blue,Unknown,Marvel Comics,83.0,183.0
477,Yellowjacket II,0,0,0,0,0,0,0,0,0,...,0,Female,Human,good,Strawberry Blond,blue,Unknown,Marvel Comics,52.0,165.0
478,Yoda,0,0,1,0,0,0,0,0,0,...,0,Male,Yoda's species,good,White,brown,green,George Lucas,17.0,66.0
479,Zatanna,0,0,0,0,0,0,0,0,0,...,0,Female,Human,good,Black,blue,Unknown,DC Comics,57.0,170.0
480,Zoom,0,0,0,0,0,0,0,0,0,...,0,Male,Unknown,bad,Brown,red,Unknown,DC Comics,81.0,185.0

In [182]:
# Calculate average weight for heroes with and without Super Speed
average_weight_with_super_speed = sh_final[sh_final['Super_Speed'] == 1]['Weight_kg'].mean()
average_weight_without_super_speed = sh_final[sh_final['Super_Speed'] == 0]['Weight_kg'].mean()

print("Average weight for heroes with Super Speed:", average_weight_with_super_speed)
print("Average weight for heroes without Super Speed:", average_weight_without_super_speed)

Average weight for heroes with Super Speed: 126.0233644859813
Average weight for heroes without Super Speed: 101.4494382022472

In [184]:
average_height_by_publisher = sh_final.groupby('Publisher')['Height_cm'].mean()

print("Average height of heroes by publisher:")
print(average_height_by_publisher)

Average height of heroes by publisher:
Publisher
DC Comics            181.927083
Dark Horse Comics    176.909091
George Lucas         159.600000
Image Comics         211.000000
Marvel Comics        190.955340
Shueisha             171.500000
Star Trek            181.500000
Team Epic TV         180.750000
Unknown              178.000000
Name: Height_cm, dtype: float64